// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package gtsmodel

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"time"
)

// weaver.InstanceOf checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.1 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Account)(nil)

type __is_Account[T ~struct {
	weaver.AutoMarshal
	ID                      string           "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt               time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt               time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	FetchedAt               time.Time        "bun:\"type:timestamptz,nullzero\""
	Username                string           "bun:\",nullzero,notnull,unique:usernamedomain\""
	Domain                  string           "bun:\",nullzero,unique:usernamedomain\""
	AvatarMediaAttachmentID string           "bun:\"type:CHAR(26),nullzero\""
	AvatarMediaAttachment   *MediaAttachment "bun:\"rel:belongs-to\""
	AvatarRemoteURL         string           "bun:\",nullzero\""
	HeaderMediaAttachmentID string           "bun:\"type:CHAR(26),nullzero\""
	HeaderMediaAttachment   *MediaAttachment "bun:\"rel:belongs-to\""
	HeaderRemoteURL         string           "bun:\",nullzero\""
	DisplayName             string           "bun:\"\""
	EmojiIDs                []string         "bun:\"emojis,array\""
	Emojis                  []*Emoji         "bun:\"attached_emojis,m2m:account_to_emojis\""
	Fields                  []*Field
	FieldsRaw               []*Field
	Note                    string     "bun:\"\""
	NoteRaw                 string     "bun:\"\""
	Memorial                *bool      "bun:\",default:false\""
	AlsoKnownAsURIs         []string   "bun:\"also_known_as_uris,array\""
	MovedToURI              string     "bun:\",nullzero\""
	Bot                     *bool      "bun:\",default:false\""
	Reason                  string     "bun:\"\""
	Locked                  *bool      "bun:\",default:true\""
	Discoverable            *bool      "bun:\",default:false\""
	Privacy                 Visibility "bun:\",nullzero\""
	Sensitive               *bool      "bun:\",default:false\""
	Language                string     "bun:\",nullzero,notnull,default:'en'\""
	StatusContentType       string     "bun:\",nullzero\""
	CustomCSS               string     "bun:\",nullzero\""
	URI                     string     "bun:\",nullzero,notnull,unique\""
	URL                     string     "bun:\",nullzero,unique\""
	InboxURI                string     "bun:\",nullzero,unique\""
	SharedInboxURI          *string    "bun:\"\""
	OutboxURI               string     "bun:\",nullzero,unique\""
	FollowingURI            string     "bun:\",nullzero,unique\""
	FollowersURI            string     "bun:\",nullzero,unique\""
	FeaturedCollectionURI   string     "bun:\",nullzero,unique\""
	ActorType               string     "bun:\",nullzero,notnull\""
	PrivateKey              PrivateKey "bun:\"\""
	PublicKey               PublicKey  "bun:\",notnull\""
	PublicKeyURI            string     "bun:\",nullzero,notnull,unique\""
	PublicKeyExpiresAt      time.Time  "bun:\"type:timestamptz,nullzero\""
	SensitizedAt            time.Time  "bun:\"type:timestamptz,nullzero\""
	SilencedAt              time.Time  "bun:\"type:timestamptz,nullzero\""
	SuspendedAt             time.Time  "bun:\"type:timestamptz,nullzero\""
	HideCollections         *bool      "bun:\",default:false\""
	SuspensionOrigin        string     "bun:\"type:CHAR(26),nullzero\""
	EnableRSS               *bool      "bun:\",default:false\""
}] struct{}

var _ __is_Account[Account]

func (x *Account) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.EncodeBinaryMarshaler(&x.FetchedAt)
	enc.String(x.Username)
	enc.String(x.Domain)
	enc.String(x.AvatarMediaAttachmentID)
	serviceweaver_enc_ptr_MediaAttachment_445699da(enc, x.AvatarMediaAttachment)
	enc.String(x.AvatarRemoteURL)
	enc.String(x.HeaderMediaAttachmentID)
	serviceweaver_enc_ptr_MediaAttachment_445699da(enc, x.HeaderMediaAttachment)
	enc.String(x.HeaderRemoteURL)
	enc.String(x.DisplayName)
	serviceweaver_enc_slice_string_4af10117(enc, x.EmojiIDs)
	serviceweaver_enc_slice_ptr_Emoji_12049057(enc, x.Emojis)
	serviceweaver_enc_slice_ptr_Field_01350256(enc, x.Fields)
	serviceweaver_enc_slice_ptr_Field_01350256(enc, x.FieldsRaw)
	enc.String(x.Note)
	enc.String(x.NoteRaw)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Memorial)
	serviceweaver_enc_slice_string_4af10117(enc, x.AlsoKnownAsURIs)
	enc.String(x.MovedToURI)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Bot)
	enc.String(x.Reason)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Locked)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Discoverable)
	enc.String((string)(x.Privacy))
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Sensitive)
	enc.String(x.Language)
	enc.String(x.StatusContentType)
	enc.String(x.CustomCSS)
	enc.String(x.URI)
	enc.String(x.URL)
	enc.String(x.InboxURI)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.SharedInboxURI)
	enc.String(x.OutboxURI)
	enc.String(x.FollowingURI)
	enc.String(x.FollowersURI)
	enc.String(x.FeaturedCollectionURI)
	enc.String(x.ActorType)
	enc.EncodeBinaryMarshaler(&x.PrivateKey)
	enc.EncodeBinaryMarshaler(&x.PublicKey)
	enc.String(x.PublicKeyURI)
	enc.EncodeBinaryMarshaler(&x.PublicKeyExpiresAt)
	enc.EncodeBinaryMarshaler(&x.SensitizedAt)
	enc.EncodeBinaryMarshaler(&x.SilencedAt)
	enc.EncodeBinaryMarshaler(&x.SuspendedAt)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.HideCollections)
	enc.String(x.SuspensionOrigin)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.EnableRSS)
}

func (x *Account) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	dec.DecodeBinaryUnmarshaler(&x.FetchedAt)
	x.Username = dec.String()
	x.Domain = dec.String()
	x.AvatarMediaAttachmentID = dec.String()
	x.AvatarMediaAttachment = serviceweaver_dec_ptr_MediaAttachment_445699da(dec)
	x.AvatarRemoteURL = dec.String()
	x.HeaderMediaAttachmentID = dec.String()
	x.HeaderMediaAttachment = serviceweaver_dec_ptr_MediaAttachment_445699da(dec)
	x.HeaderRemoteURL = dec.String()
	x.DisplayName = dec.String()
	x.EmojiIDs = serviceweaver_dec_slice_string_4af10117(dec)
	x.Emojis = serviceweaver_dec_slice_ptr_Emoji_12049057(dec)
	x.Fields = serviceweaver_dec_slice_ptr_Field_01350256(dec)
	x.FieldsRaw = serviceweaver_dec_slice_ptr_Field_01350256(dec)
	x.Note = dec.String()
	x.NoteRaw = dec.String()
	x.Memorial = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.AlsoKnownAsURIs = serviceweaver_dec_slice_string_4af10117(dec)
	x.MovedToURI = dec.String()
	x.Bot = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Reason = dec.String()
	x.Locked = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Discoverable = serviceweaver_dec_ptr_bool_31f02903(dec)
	*(*string)(&x.Privacy) = dec.String()
	x.Sensitive = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Language = dec.String()
	x.StatusContentType = dec.String()
	x.CustomCSS = dec.String()
	x.URI = dec.String()
	x.URL = dec.String()
	x.InboxURI = dec.String()
	x.SharedInboxURI = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.OutboxURI = dec.String()
	x.FollowingURI = dec.String()
	x.FollowersURI = dec.String()
	x.FeaturedCollectionURI = dec.String()
	x.ActorType = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.PrivateKey)
	dec.DecodeBinaryUnmarshaler(&x.PublicKey)
	x.PublicKeyURI = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.PublicKeyExpiresAt)
	dec.DecodeBinaryUnmarshaler(&x.SensitizedAt)
	dec.DecodeBinaryUnmarshaler(&x.SilencedAt)
	dec.DecodeBinaryUnmarshaler(&x.SuspendedAt)
	x.HideCollections = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.SuspensionOrigin = dec.String()
	x.EnableRSS = serviceweaver_dec_ptr_bool_31f02903(dec)
}

func serviceweaver_enc_ptr_MediaAttachment_445699da(enc *codegen.Encoder, arg *MediaAttachment) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_MediaAttachment_445699da(dec *codegen.Decoder) *MediaAttachment {
	if !dec.Bool() {
		return nil
	}
	var res MediaAttachment
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func serviceweaver_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

func serviceweaver_enc_ptr_Emoji_0cfa95c6(enc *codegen.Encoder, arg *Emoji) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_Emoji_0cfa95c6(dec *codegen.Decoder) *Emoji {
	if !dec.Bool() {
		return nil
	}
	var res Emoji
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_slice_ptr_Emoji_12049057(enc *codegen.Encoder, arg []*Emoji) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		serviceweaver_enc_ptr_Emoji_0cfa95c6(enc, arg[i])
	}
}

func serviceweaver_dec_slice_ptr_Emoji_12049057(dec *codegen.Decoder) []*Emoji {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*Emoji, n)
	for i := 0; i < n; i++ {
		res[i] = serviceweaver_dec_ptr_Emoji_0cfa95c6(dec)
	}
	return res
}

func serviceweaver_enc_ptr_Field_0f5504f6(enc *codegen.Encoder, arg *Field) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_Field_0f5504f6(dec *codegen.Decoder) *Field {
	if !dec.Bool() {
		return nil
	}
	var res Field
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_slice_ptr_Field_01350256(enc *codegen.Encoder, arg []*Field) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		serviceweaver_enc_ptr_Field_0f5504f6(enc, arg[i])
	}
}

func serviceweaver_dec_slice_ptr_Field_01350256(dec *codegen.Decoder) []*Field {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*Field, n)
	for i := 0; i < n; i++ {
		res[i] = serviceweaver_dec_ptr_Field_0f5504f6(dec)
	}
	return res
}

func serviceweaver_enc_ptr_bool_31f02903(enc *codegen.Encoder, arg *bool) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Bool(*arg)
	}
}

func serviceweaver_dec_ptr_bool_31f02903(dec *codegen.Decoder) *bool {
	if !dec.Bool() {
		return nil
	}
	var res bool
	res = dec.Bool()
	return &res
}

func serviceweaver_enc_ptr_string_3e89801b(enc *codegen.Encoder, arg *string) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.String(*arg)
	}
}

func serviceweaver_dec_ptr_string_3e89801b(dec *codegen.Decoder) *string {
	if !dec.Bool() {
		return nil
	}
	var res string
	res = dec.String()
	return &res
}

var _ codegen.AutoMarshal = (*Application)(nil)

type __is_Application[T ~struct {
	weaver.AutoMarshal
	ID           string    "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt    time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt    time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Name         string    "bun:\",notnull\""
	Website      string    "bun:\",nullzero\""
	RedirectURI  string    "bun:\",nullzero,notnull\""
	ClientID     string    "bun:\"type:CHAR(26),nullzero,notnull\""
	ClientSecret string    "bun:\",nullzero,notnull\""
	Scopes       string    "bun:\",notnull\""
}] struct{}

var _ __is_Application[Application]

func (x *Application) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Name)
	enc.String(x.Website)
	enc.String(x.RedirectURI)
	enc.String(x.ClientID)
	enc.String(x.ClientSecret)
	enc.String(x.Scopes)
}

func (x *Application) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Name = dec.String()
	x.Website = dec.String()
	x.RedirectURI = dec.String()
	x.ClientID = dec.String()
	x.ClientSecret = dec.String()
	x.Scopes = dec.String()
}

var _ codegen.AutoMarshal = (*Emoji)(nil)

type __is_Emoji[T ~struct {
	weaver.AutoMarshal
	ID                     string         "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt              time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt              time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Shortcode              string         "bun:\",nullzero,notnull,unique:domainshortcode\""
	Domain                 string         "bun:\",nullzero,unique:domainshortcode\""
	ImageRemoteURL         string         "bun:\",nullzero\""
	ImageStaticRemoteURL   string         "bun:\",nullzero\""
	ImageURL               string         "bun:\",nullzero\""
	ImageStaticURL         string         "bun:\",nullzero\""
	ImagePath              string         "bun:\",nullzero,notnull\""
	ImageStaticPath        string         "bun:\",nullzero,notnull\""
	ImageContentType       string         "bun:\",nullzero,notnull\""
	ImageStaticContentType string         "bun:\",nullzero,notnull\""
	ImageFileSize          int            "bun:\",nullzero,notnull\""
	ImageStaticFileSize    int            "bun:\",nullzero,notnull\""
	ImageUpdatedAt         time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Disabled               *bool          "bun:\",nullzero,notnull,default:false\""
	URI                    string         "bun:\",nullzero,notnull,unique\""
	VisibleInPicker        *bool          "bun:\",nullzero,notnull,default:true\""
	Category               *EmojiCategory "bun:\"rel:belongs-to\""
	CategoryID             string         "bun:\"type:CHAR(26),nullzero\""
	Cached                 *bool          "bun:\",nullzero,notnull,default:false\""
}] struct{}

var _ __is_Emoji[Emoji]

func (x *Emoji) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Emoji.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Shortcode)
	enc.String(x.Domain)
	enc.String(x.ImageRemoteURL)
	enc.String(x.ImageStaticRemoteURL)
	enc.String(x.ImageURL)
	enc.String(x.ImageStaticURL)
	enc.String(x.ImagePath)
	enc.String(x.ImageStaticPath)
	enc.String(x.ImageContentType)
	enc.String(x.ImageStaticContentType)
	enc.Int(x.ImageFileSize)
	enc.Int(x.ImageStaticFileSize)
	enc.EncodeBinaryMarshaler(&x.ImageUpdatedAt)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Disabled)
	enc.String(x.URI)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.VisibleInPicker)
	serviceweaver_enc_ptr_EmojiCategory_ede98795(enc, x.Category)
	enc.String(x.CategoryID)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Cached)
}

func (x *Emoji) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Emoji.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Shortcode = dec.String()
	x.Domain = dec.String()
	x.ImageRemoteURL = dec.String()
	x.ImageStaticRemoteURL = dec.String()
	x.ImageURL = dec.String()
	x.ImageStaticURL = dec.String()
	x.ImagePath = dec.String()
	x.ImageStaticPath = dec.String()
	x.ImageContentType = dec.String()
	x.ImageStaticContentType = dec.String()
	x.ImageFileSize = dec.Int()
	x.ImageStaticFileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.ImageUpdatedAt)
	x.Disabled = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.URI = dec.String()
	x.VisibleInPicker = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Category = serviceweaver_dec_ptr_EmojiCategory_ede98795(dec)
	x.CategoryID = dec.String()
	x.Cached = serviceweaver_dec_ptr_bool_31f02903(dec)
}

func serviceweaver_enc_ptr_EmojiCategory_ede98795(enc *codegen.Encoder, arg *EmojiCategory) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_EmojiCategory_ede98795(dec *codegen.Decoder) *EmojiCategory {
	if !dec.Bool() {
		return nil
	}
	var res EmojiCategory
	(&res).WeaverUnmarshal(dec)
	return &res
}

var _ codegen.AutoMarshal = (*EmojiCategory)(nil)

type __is_EmojiCategory[T ~struct {
	weaver.AutoMarshal
	ID        string    "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Name      string    "bun:\",nullzero,notnull,unique\""
}] struct{}

var _ __is_EmojiCategory[EmojiCategory]

func (x *EmojiCategory) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("EmojiCategory.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Name)
}

func (x *EmojiCategory) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("EmojiCategory.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Name = dec.String()
}

var _ codegen.AutoMarshal = (*Field)(nil)

type __is_Field[T ~struct {
	weaver.AutoMarshal
	Name       string
	Value      string
	VerifiedAt time.Time "bun:\",nullzero\""
}] struct{}

var _ __is_Field[Field]

func (x *Field) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Field.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Name)
	enc.String(x.Value)
	enc.EncodeBinaryMarshaler(&x.VerifiedAt)
}

func (x *Field) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Field.WeaverUnmarshal: nil receiver"))
	}
	x.Name = dec.String()
	x.Value = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.VerifiedAt)
}

var _ codegen.AutoMarshal = (*File)(nil)

type __is_File[T ~struct {
	weaver.AutoMarshal
	Path        string    "bun:\",nullzero,notnull\""
	ContentType string    "bun:\",nullzero,notnull\""
	FileSize    int       "bun:\",notnull\""
	UpdatedAt   time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
}] struct{}

var _ __is_File[File]

func (x *File) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("File.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Path)
	enc.String(x.ContentType)
	enc.Int(x.FileSize)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
}

func (x *File) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("File.WeaverUnmarshal: nil receiver"))
	}
	x.Path = dec.String()
	x.ContentType = dec.String()
	x.FileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
}

var _ codegen.AutoMarshal = (*FileMeta)(nil)

type __is_FileMeta[T ~struct {
	weaver.AutoMarshal
	Original Original "bun:\"embed:original_\""
	Small    Small    "bun:\"embed:small_\""
	Focus    Focus    "bun:\"embed:focus_\""
}] struct{}

var _ __is_FileMeta[FileMeta]

func (x *FileMeta) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("FileMeta.WeaverMarshal: nil receiver"))
	}
	(x.Original).WeaverMarshal(enc)
	(x.Small).WeaverMarshal(enc)
	(x.Focus).WeaverMarshal(enc)
}

func (x *FileMeta) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("FileMeta.WeaverUnmarshal: nil receiver"))
	}
	(&x.Original).WeaverUnmarshal(dec)
	(&x.Small).WeaverUnmarshal(dec)
	(&x.Focus).WeaverUnmarshal(dec)
}

var _ codegen.AutoMarshal = (*Focus)(nil)

type __is_Focus[T ~struct {
	weaver.AutoMarshal
	X float32
	Y float32
}] struct{}

var _ __is_Focus[Focus]

func (x *Focus) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Focus.WeaverMarshal: nil receiver"))
	}
	enc.Float32(x.X)
	enc.Float32(x.Y)
}

func (x *Focus) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Focus.WeaverUnmarshal: nil receiver"))
	}
	x.X = dec.Float32()
	x.Y = dec.Float32()
}

var _ codegen.AutoMarshal = (*MediaAttachment)(nil)

type __is_MediaAttachment[T ~struct {
	weaver.AutoMarshal
	ID                string           "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt         time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt         time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	StatusID          string           "bun:\"type:CHAR(26),nullzero\""
	URL               string           "bun:\",nullzero\""
	RemoteURL         string           "bun:\",nullzero\""
	Type              FileType         "bun:\",nullzero,notnull\""
	FileMeta          FileMeta         "bun:\",embed:,nullzero,notnull\""
	AccountID         string           "bun:\"type:CHAR(26),nullzero,notnull\""
	Description       string           "bun:\"\""
	ScheduledStatusID string           "bun:\"type:CHAR(26),nullzero\""
	Blurhash          string           "bun:\",nullzero\""
	Processing        ProcessingStatus "bun:\",notnull,default:2\""
	File              File             "bun:\",embed:file_,notnull,nullzero\""
	Thumbnail         Thumbnail        "bun:\",embed:thumbnail_,notnull,nullzero\""
	Avatar            *bool            "bun:\",nullzero,notnull,default:false\""
	Header            *bool            "bun:\",nullzero,notnull,default:false\""
	Cached            *bool            "bun:\",nullzero,notnull,default:false\""
}] struct{}

var _ __is_MediaAttachment[MediaAttachment]

func (x *MediaAttachment) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MediaAttachment.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.StatusID)
	enc.String(x.URL)
	enc.String(x.RemoteURL)
	enc.String((string)(x.Type))
	(x.FileMeta).WeaverMarshal(enc)
	enc.String(x.AccountID)
	enc.String(x.Description)
	enc.String(x.ScheduledStatusID)
	enc.String(x.Blurhash)
	enc.Int((int)(x.Processing))
	(x.File).WeaverMarshal(enc)
	(x.Thumbnail).WeaverMarshal(enc)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Avatar)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Header)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Cached)
}

func (x *MediaAttachment) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MediaAttachment.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.StatusID = dec.String()
	x.URL = dec.String()
	x.RemoteURL = dec.String()
	*(*string)(&x.Type) = dec.String()
	(&x.FileMeta).WeaverUnmarshal(dec)
	x.AccountID = dec.String()
	x.Description = dec.String()
	x.ScheduledStatusID = dec.String()
	x.Blurhash = dec.String()
	*(*int)(&x.Processing) = dec.Int()
	(&x.File).WeaverUnmarshal(dec)
	(&x.Thumbnail).WeaverUnmarshal(dec)
	x.Avatar = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Header = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Cached = serviceweaver_dec_ptr_bool_31f02903(dec)
}

var _ codegen.AutoMarshal = (*Original)(nil)

type __is_Original[T ~struct {
	weaver.AutoMarshal
	Width     int
	Height    int
	Size      int
	Aspect    float32
	Duration  *float32
	Framerate *float32
	Bitrate   *uint64
}] struct{}

var _ __is_Original[Original]

func (x *Original) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Original.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.Width)
	enc.Int(x.Height)
	enc.Int(x.Size)
	enc.Float32(x.Aspect)
	serviceweaver_enc_ptr_float32_2a388dbf(enc, x.Duration)
	serviceweaver_enc_ptr_float32_2a388dbf(enc, x.Framerate)
	serviceweaver_enc_ptr_uint64_87cde9b6(enc, x.Bitrate)
}

func (x *Original) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Original.WeaverUnmarshal: nil receiver"))
	}
	x.Width = dec.Int()
	x.Height = dec.Int()
	x.Size = dec.Int()
	x.Aspect = dec.Float32()
	x.Duration = serviceweaver_dec_ptr_float32_2a388dbf(dec)
	x.Framerate = serviceweaver_dec_ptr_float32_2a388dbf(dec)
	x.Bitrate = serviceweaver_dec_ptr_uint64_87cde9b6(dec)
}

func serviceweaver_enc_ptr_float32_2a388dbf(enc *codegen.Encoder, arg *float32) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Float32(*arg)
	}
}

func serviceweaver_dec_ptr_float32_2a388dbf(dec *codegen.Decoder) *float32 {
	if !dec.Bool() {
		return nil
	}
	var res float32
	res = dec.Float32()
	return &res
}

func serviceweaver_enc_ptr_uint64_87cde9b6(enc *codegen.Encoder, arg *uint64) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Uint64(*arg)
	}
}

func serviceweaver_dec_ptr_uint64_87cde9b6(dec *codegen.Decoder) *uint64 {
	if !dec.Bool() {
		return nil
	}
	var res uint64
	res = dec.Uint64()
	return &res
}

var _ codegen.AutoMarshal = (*Relationship)(nil)

type __is_Relationship[T ~struct {
	weaver.AutoMarshal
	ID                  string
	Following           bool
	ShowingReblogs      bool
	Notifying           bool
	FollowedBy          bool
	Blocking            bool
	BlockedBy           bool
	Muting              bool
	MutingNotifications bool
	Requested           bool
	RequestedBy         bool
	DomainBlocking      bool
	Endorsed            bool
	Note                string
}] struct{}

var _ __is_Relationship[Relationship]

func (x *Relationship) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Relationship.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.Bool(x.Following)
	enc.Bool(x.ShowingReblogs)
	enc.Bool(x.Notifying)
	enc.Bool(x.FollowedBy)
	enc.Bool(x.Blocking)
	enc.Bool(x.BlockedBy)
	enc.Bool(x.Muting)
	enc.Bool(x.MutingNotifications)
	enc.Bool(x.Requested)
	enc.Bool(x.RequestedBy)
	enc.Bool(x.DomainBlocking)
	enc.Bool(x.Endorsed)
	enc.String(x.Note)
}

func (x *Relationship) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Relationship.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Following = dec.Bool()
	x.ShowingReblogs = dec.Bool()
	x.Notifying = dec.Bool()
	x.FollowedBy = dec.Bool()
	x.Blocking = dec.Bool()
	x.BlockedBy = dec.Bool()
	x.Muting = dec.Bool()
	x.MutingNotifications = dec.Bool()
	x.Requested = dec.Bool()
	x.RequestedBy = dec.Bool()
	x.DomainBlocking = dec.Bool()
	x.Endorsed = dec.Bool()
	x.Note = dec.String()
}

var _ codegen.AutoMarshal = (*Small)(nil)

type __is_Small[T ~struct {
	weaver.AutoMarshal
	Width  int
	Height int
	Size   int
	Aspect float32
}] struct{}

var _ __is_Small[Small]

func (x *Small) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Small.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.Width)
	enc.Int(x.Height)
	enc.Int(x.Size)
	enc.Float32(x.Aspect)
}

func (x *Small) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Small.WeaverUnmarshal: nil receiver"))
	}
	x.Width = dec.Int()
	x.Height = dec.Int()
	x.Size = dec.Int()
	x.Aspect = dec.Float32()
}

var _ codegen.AutoMarshal = (*Thumbnail)(nil)

type __is_Thumbnail[T ~struct {
	weaver.AutoMarshal
	Path        string    "bun:\",nullzero,notnull\""
	ContentType string    "bun:\",nullzero,notnull\""
	FileSize    int       "bun:\",notnull\""
	UpdatedAt   time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	URL         string    "bun:\",nullzero\""
	RemoteURL   string    "bun:\",nullzero\""
}] struct{}

var _ __is_Thumbnail[Thumbnail]

func (x *Thumbnail) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Thumbnail.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Path)
	enc.String(x.ContentType)
	enc.Int(x.FileSize)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.URL)
	enc.String(x.RemoteURL)
}

func (x *Thumbnail) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Thumbnail.WeaverUnmarshal: nil receiver"))
	}
	x.Path = dec.String()
	x.ContentType = dec.String()
	x.FileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.URL = dec.String()
	x.RemoteURL = dec.String()
}
