// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package gtsmodel

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"time"
)

// weaver.InstanceOf checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.1 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Application)(nil)

type __is_Application[T ~struct {
	weaver.AutoMarshal
	ID           string    "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt    time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt    time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Name         string    "bun:\",notnull\""
	Website      string    "bun:\",nullzero\""
	RedirectURI  string    "bun:\",nullzero,notnull\""
	ClientID     string    "bun:\"type:CHAR(26),nullzero,notnull\""
	ClientSecret string    "bun:\",nullzero,notnull\""
	Scopes       string    "bun:\",notnull\""
}] struct{}

var _ __is_Application[Application]

func (x *Application) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Name)
	enc.String(x.Website)
	enc.String(x.RedirectURI)
	enc.String(x.ClientID)
	enc.String(x.ClientSecret)
	enc.String(x.Scopes)
}

func (x *Application) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Name = dec.String()
	x.Website = dec.String()
	x.RedirectURI = dec.String()
	x.ClientID = dec.String()
	x.ClientSecret = dec.String()
	x.Scopes = dec.String()
}

var _ codegen.AutoMarshal = (*Emoji)(nil)

type __is_Emoji[T ~struct {
	weaver.AutoMarshal
	ID                     string         "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt              time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt              time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Shortcode              string         "bun:\",nullzero,notnull,unique:domainshortcode\""
	Domain                 string         "bun:\",nullzero,unique:domainshortcode\""
	ImageRemoteURL         string         "bun:\",nullzero\""
	ImageStaticRemoteURL   string         "bun:\",nullzero\""
	ImageURL               string         "bun:\",nullzero\""
	ImageStaticURL         string         "bun:\",nullzero\""
	ImagePath              string         "bun:\",nullzero,notnull\""
	ImageStaticPath        string         "bun:\",nullzero,notnull\""
	ImageContentType       string         "bun:\",nullzero,notnull\""
	ImageStaticContentType string         "bun:\",nullzero,notnull\""
	ImageFileSize          int            "bun:\",nullzero,notnull\""
	ImageStaticFileSize    int            "bun:\",nullzero,notnull\""
	ImageUpdatedAt         time.Time      "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Disabled               *bool          "bun:\",nullzero,notnull,default:false\""
	URI                    string         "bun:\",nullzero,notnull,unique\""
	VisibleInPicker        *bool          "bun:\",nullzero,notnull,default:true\""
	Category               *EmojiCategory "bun:\"rel:belongs-to\""
	CategoryID             string         "bun:\"type:CHAR(26),nullzero\""
	Cached                 *bool          "bun:\",nullzero,notnull,default:false\""
}] struct{}

var _ __is_Emoji[Emoji]

func (x *Emoji) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Emoji.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Shortcode)
	enc.String(x.Domain)
	enc.String(x.ImageRemoteURL)
	enc.String(x.ImageStaticRemoteURL)
	enc.String(x.ImageURL)
	enc.String(x.ImageStaticURL)
	enc.String(x.ImagePath)
	enc.String(x.ImageStaticPath)
	enc.String(x.ImageContentType)
	enc.String(x.ImageStaticContentType)
	enc.Int(x.ImageFileSize)
	enc.Int(x.ImageStaticFileSize)
	enc.EncodeBinaryMarshaler(&x.ImageUpdatedAt)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Disabled)
	enc.String(x.URI)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.VisibleInPicker)
	serviceweaver_enc_ptr_EmojiCategory_ede98795(enc, x.Category)
	enc.String(x.CategoryID)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Cached)
}

func (x *Emoji) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Emoji.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Shortcode = dec.String()
	x.Domain = dec.String()
	x.ImageRemoteURL = dec.String()
	x.ImageStaticRemoteURL = dec.String()
	x.ImageURL = dec.String()
	x.ImageStaticURL = dec.String()
	x.ImagePath = dec.String()
	x.ImageStaticPath = dec.String()
	x.ImageContentType = dec.String()
	x.ImageStaticContentType = dec.String()
	x.ImageFileSize = dec.Int()
	x.ImageStaticFileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.ImageUpdatedAt)
	x.Disabled = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.URI = dec.String()
	x.VisibleInPicker = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Category = serviceweaver_dec_ptr_EmojiCategory_ede98795(dec)
	x.CategoryID = dec.String()
	x.Cached = serviceweaver_dec_ptr_bool_31f02903(dec)
}

func serviceweaver_enc_ptr_bool_31f02903(enc *codegen.Encoder, arg *bool) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Bool(*arg)
	}
}

func serviceweaver_dec_ptr_bool_31f02903(dec *codegen.Decoder) *bool {
	if !dec.Bool() {
		return nil
	}
	var res bool
	res = dec.Bool()
	return &res
}

func serviceweaver_enc_ptr_EmojiCategory_ede98795(enc *codegen.Encoder, arg *EmojiCategory) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_EmojiCategory_ede98795(dec *codegen.Decoder) *EmojiCategory {
	if !dec.Bool() {
		return nil
	}
	var res EmojiCategory
	(&res).WeaverUnmarshal(dec)
	return &res
}

var _ codegen.AutoMarshal = (*EmojiCategory)(nil)

type __is_EmojiCategory[T ~struct {
	weaver.AutoMarshal
	ID        string    "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	Name      string    "bun:\",nullzero,notnull,unique\""
}] struct{}

var _ __is_EmojiCategory[EmojiCategory]

func (x *EmojiCategory) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("EmojiCategory.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.Name)
}

func (x *EmojiCategory) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("EmojiCategory.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.Name = dec.String()
}

var _ codegen.AutoMarshal = (*Field)(nil)

type __is_Field[T ~struct {
	weaver.AutoMarshal
	Name       string
	Value      string
	VerifiedAt time.Time "bun:\",nullzero\""
}] struct{}

var _ __is_Field[Field]

func (x *Field) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Field.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Name)
	enc.String(x.Value)
	enc.EncodeBinaryMarshaler(&x.VerifiedAt)
}

func (x *Field) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Field.WeaverUnmarshal: nil receiver"))
	}
	x.Name = dec.String()
	x.Value = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.VerifiedAt)
}

var _ codegen.AutoMarshal = (*File)(nil)

type __is_File[T ~struct {
	weaver.AutoMarshal
	Path        string    "bun:\",nullzero,notnull\""
	ContentType string    "bun:\",nullzero,notnull\""
	FileSize    int       "bun:\",notnull\""
	UpdatedAt   time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
}] struct{}

var _ __is_File[File]

func (x *File) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("File.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Path)
	enc.String(x.ContentType)
	enc.Int(x.FileSize)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
}

func (x *File) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("File.WeaverUnmarshal: nil receiver"))
	}
	x.Path = dec.String()
	x.ContentType = dec.String()
	x.FileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
}

var _ codegen.AutoMarshal = (*FileMeta)(nil)

type __is_FileMeta[T ~struct {
	weaver.AutoMarshal
	Original Original "bun:\"embed:original_\""
	Small    Small    "bun:\"embed:small_\""
	Focus    Focus    "bun:\"embed:focus_\""
}] struct{}

var _ __is_FileMeta[FileMeta]

func (x *FileMeta) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("FileMeta.WeaverMarshal: nil receiver"))
	}
	(x.Original).WeaverMarshal(enc)
	(x.Small).WeaverMarshal(enc)
	(x.Focus).WeaverMarshal(enc)
}

func (x *FileMeta) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("FileMeta.WeaverUnmarshal: nil receiver"))
	}
	(&x.Original).WeaverUnmarshal(dec)
	(&x.Small).WeaverUnmarshal(dec)
	(&x.Focus).WeaverUnmarshal(dec)
}

var _ codegen.AutoMarshal = (*Focus)(nil)

type __is_Focus[T ~struct {
	weaver.AutoMarshal
	X float32
	Y float32
}] struct{}

var _ __is_Focus[Focus]

func (x *Focus) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Focus.WeaverMarshal: nil receiver"))
	}
	enc.Float32(x.X)
	enc.Float32(x.Y)
}

func (x *Focus) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Focus.WeaverUnmarshal: nil receiver"))
	}
	x.X = dec.Float32()
	x.Y = dec.Float32()
}

var _ codegen.AutoMarshal = (*MediaAttachment)(nil)

type __is_MediaAttachment[T ~struct {
	weaver.AutoMarshal
	ID                string           "bun:\"type:CHAR(26),pk,nullzero,notnull,unique\""
	CreatedAt         time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	UpdatedAt         time.Time        "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	StatusID          string           "bun:\"type:CHAR(26),nullzero\""
	URL               string           "bun:\",nullzero\""
	RemoteURL         string           "bun:\",nullzero\""
	Type              FileType         "bun:\",nullzero,notnull\""
	FileMeta          FileMeta         "bun:\",embed:,nullzero,notnull\""
	AccountID         string           "bun:\"type:CHAR(26),nullzero,notnull\""
	Description       string           "bun:\"\""
	ScheduledStatusID string           "bun:\"type:CHAR(26),nullzero\""
	Blurhash          string           "bun:\",nullzero\""
	Processing        ProcessingStatus "bun:\",notnull,default:2\""
	File              File             "bun:\",embed:file_,notnull,nullzero\""
	Thumbnail         Thumbnail        "bun:\",embed:thumbnail_,notnull,nullzero\""
	Avatar            *bool            "bun:\",nullzero,notnull,default:false\""
	Header            *bool            "bun:\",nullzero,notnull,default:false\""
	Cached            *bool            "bun:\",nullzero,notnull,default:false\""
}] struct{}

var _ __is_MediaAttachment[MediaAttachment]

func (x *MediaAttachment) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MediaAttachment.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.StatusID)
	enc.String(x.URL)
	enc.String(x.RemoteURL)
	enc.String((string)(x.Type))
	(x.FileMeta).WeaverMarshal(enc)
	enc.String(x.AccountID)
	enc.String(x.Description)
	enc.String(x.ScheduledStatusID)
	enc.String(x.Blurhash)
	enc.Int((int)(x.Processing))
	(x.File).WeaverMarshal(enc)
	(x.Thumbnail).WeaverMarshal(enc)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Avatar)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Header)
	serviceweaver_enc_ptr_bool_31f02903(enc, x.Cached)
}

func (x *MediaAttachment) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MediaAttachment.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.StatusID = dec.String()
	x.URL = dec.String()
	x.RemoteURL = dec.String()
	*(*string)(&x.Type) = dec.String()
	(&x.FileMeta).WeaverUnmarshal(dec)
	x.AccountID = dec.String()
	x.Description = dec.String()
	x.ScheduledStatusID = dec.String()
	x.Blurhash = dec.String()
	*(*int)(&x.Processing) = dec.Int()
	(&x.File).WeaverUnmarshal(dec)
	(&x.Thumbnail).WeaverUnmarshal(dec)
	x.Avatar = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Header = serviceweaver_dec_ptr_bool_31f02903(dec)
	x.Cached = serviceweaver_dec_ptr_bool_31f02903(dec)
}

var _ codegen.AutoMarshal = (*Original)(nil)

type __is_Original[T ~struct {
	weaver.AutoMarshal
	Width     int
	Height    int
	Size      int
	Aspect    float32
	Duration  *float32
	Framerate *float32
	Bitrate   *uint64
}] struct{}

var _ __is_Original[Original]

func (x *Original) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Original.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.Width)
	enc.Int(x.Height)
	enc.Int(x.Size)
	enc.Float32(x.Aspect)
	serviceweaver_enc_ptr_float32_2a388dbf(enc, x.Duration)
	serviceweaver_enc_ptr_float32_2a388dbf(enc, x.Framerate)
	serviceweaver_enc_ptr_uint64_87cde9b6(enc, x.Bitrate)
}

func (x *Original) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Original.WeaverUnmarshal: nil receiver"))
	}
	x.Width = dec.Int()
	x.Height = dec.Int()
	x.Size = dec.Int()
	x.Aspect = dec.Float32()
	x.Duration = serviceweaver_dec_ptr_float32_2a388dbf(dec)
	x.Framerate = serviceweaver_dec_ptr_float32_2a388dbf(dec)
	x.Bitrate = serviceweaver_dec_ptr_uint64_87cde9b6(dec)
}

func serviceweaver_enc_ptr_float32_2a388dbf(enc *codegen.Encoder, arg *float32) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Float32(*arg)
	}
}

func serviceweaver_dec_ptr_float32_2a388dbf(dec *codegen.Decoder) *float32 {
	if !dec.Bool() {
		return nil
	}
	var res float32
	res = dec.Float32()
	return &res
}

func serviceweaver_enc_ptr_uint64_87cde9b6(enc *codegen.Encoder, arg *uint64) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.Uint64(*arg)
	}
}

func serviceweaver_dec_ptr_uint64_87cde9b6(dec *codegen.Decoder) *uint64 {
	if !dec.Bool() {
		return nil
	}
	var res uint64
	res = dec.Uint64()
	return &res
}

var _ codegen.AutoMarshal = (*Relationship)(nil)

type __is_Relationship[T ~struct {
	weaver.AutoMarshal
	ID                  string
	Following           bool
	ShowingReblogs      bool
	Notifying           bool
	FollowedBy          bool
	Blocking            bool
	BlockedBy           bool
	Muting              bool
	MutingNotifications bool
	Requested           bool
	RequestedBy         bool
	DomainBlocking      bool
	Endorsed            bool
	Note                string
}] struct{}

var _ __is_Relationship[Relationship]

func (x *Relationship) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Relationship.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.Bool(x.Following)
	enc.Bool(x.ShowingReblogs)
	enc.Bool(x.Notifying)
	enc.Bool(x.FollowedBy)
	enc.Bool(x.Blocking)
	enc.Bool(x.BlockedBy)
	enc.Bool(x.Muting)
	enc.Bool(x.MutingNotifications)
	enc.Bool(x.Requested)
	enc.Bool(x.RequestedBy)
	enc.Bool(x.DomainBlocking)
	enc.Bool(x.Endorsed)
	enc.String(x.Note)
}

func (x *Relationship) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Relationship.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Following = dec.Bool()
	x.ShowingReblogs = dec.Bool()
	x.Notifying = dec.Bool()
	x.FollowedBy = dec.Bool()
	x.Blocking = dec.Bool()
	x.BlockedBy = dec.Bool()
	x.Muting = dec.Bool()
	x.MutingNotifications = dec.Bool()
	x.Requested = dec.Bool()
	x.RequestedBy = dec.Bool()
	x.DomainBlocking = dec.Bool()
	x.Endorsed = dec.Bool()
	x.Note = dec.String()
}

var _ codegen.AutoMarshal = (*Small)(nil)

type __is_Small[T ~struct {
	weaver.AutoMarshal
	Width  int
	Height int
	Size   int
	Aspect float32
}] struct{}

var _ __is_Small[Small]

func (x *Small) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Small.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.Width)
	enc.Int(x.Height)
	enc.Int(x.Size)
	enc.Float32(x.Aspect)
}

func (x *Small) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Small.WeaverUnmarshal: nil receiver"))
	}
	x.Width = dec.Int()
	x.Height = dec.Int()
	x.Size = dec.Int()
	x.Aspect = dec.Float32()
}

var _ codegen.AutoMarshal = (*Thumbnail)(nil)

type __is_Thumbnail[T ~struct {
	weaver.AutoMarshal
	Path        string    "bun:\",nullzero,notnull\""
	ContentType string    "bun:\",nullzero,notnull\""
	FileSize    int       "bun:\",notnull\""
	UpdatedAt   time.Time "bun:\"type:timestamptz,nullzero,notnull,default:current_timestamp\""
	URL         string    "bun:\",nullzero\""
	RemoteURL   string    "bun:\",nullzero\""
}] struct{}

var _ __is_Thumbnail[Thumbnail]

func (x *Thumbnail) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Thumbnail.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Path)
	enc.String(x.ContentType)
	enc.Int(x.FileSize)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
	enc.String(x.URL)
	enc.String(x.RemoteURL)
}

func (x *Thumbnail) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Thumbnail.WeaverUnmarshal: nil receiver"))
	}
	x.Path = dec.String()
	x.ContentType = dec.String()
	x.FileSize = dec.Int()
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
	x.URL = dec.String()
	x.RemoteURL = dec.String()
}
