// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package weaver

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"github.com/superseriousbusiness/gotosocial/internal/api/model"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/weaver/Main",
		Iface: reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:  reflect.TypeOf(App{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦58ea55b5:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→github.com/superseriousbusiness/gotosocial/internal/weaver/MediaRequestHandler⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "github.com/superseriousbusiness/gotosocial/internal/weaver/MediaRequestHandler",
		Iface: reflect.TypeOf((*MediaRequestHandler)(nil)).Elem(),
		Impl:  reflect.TypeOf(mediaRequestHandler{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return mediaRequestHandler_local_stub{impl: impl.(MediaRequestHandler), tracer: tracer, doOperationMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/superseriousbusiness/gotosocial/internal/weaver/MediaRequestHandler", Method: "DoOperation", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return mediaRequestHandler_client_stub{stub: stub, doOperationMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/superseriousbusiness/gotosocial/internal/weaver/MediaRequestHandler", Method: "DoOperation", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return mediaRequestHandler_server_stub{impl: impl.(MediaRequestHandler), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return mediaRequestHandler_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[weaver.Main] = (*App)(nil)
var _ weaver.InstanceOf[MediaRequestHandler] = (*mediaRequestHandler)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*App)(nil)
var _ weaver.Unrouted = (*mediaRequestHandler)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

type mediaRequestHandler_local_stub struct {
	impl               MediaRequestHandler
	tracer             trace.Tracer
	doOperationMetrics *codegen.MethodMetrics
}

// Check that mediaRequestHandler_local_stub implements the MediaRequestHandler interface.
var _ MediaRequestHandler = (*mediaRequestHandler_local_stub)(nil)

func (s mediaRequestHandler_local_stub) DoOperation(ctx context.Context, a0 string, a1 *model.AttachmentRequest, a2 string, a3 *model.AttachmentUpdateRequest, a4 MediaRequestOperation) (r0 *model.Attachment, err error) {
	// Update metrics.
	begin := s.doOperationMetrics.Begin()
	defer func() { s.doOperationMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "weaver.MediaRequestHandler.DoOperation", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.DoOperation(ctx, a0, a1, a2, a3, a4)
}

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

type mediaRequestHandler_client_stub struct {
	stub               codegen.Stub
	doOperationMetrics *codegen.MethodMetrics
}

// Check that mediaRequestHandler_client_stub implements the MediaRequestHandler interface.
var _ MediaRequestHandler = (*mediaRequestHandler_client_stub)(nil)

func (s mediaRequestHandler_client_stub) DoOperation(ctx context.Context, a0 string, a1 *model.AttachmentRequest, a2 string, a3 *model.AttachmentUpdateRequest, a4 MediaRequestOperation) (r0 *model.Attachment, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.doOperationMetrics.Begin()
	defer func() { s.doOperationMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "weaver.MediaRequestHandler.DoOperation", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	enc.String(a0)
	serviceweaver_enc_ptr_AttachmentRequest_26f527db(enc, a1)
	enc.String(a2)
	serviceweaver_enc_ptr_AttachmentUpdateRequest_7d9aafff(enc, a3)
	enc.Int((int)(a4))
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_Attachment_51e21580(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.1 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

type mediaRequestHandler_server_stub struct {
	impl    MediaRequestHandler
	addLoad func(key uint64, load float64)
}

// Check that mediaRequestHandler_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*mediaRequestHandler_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s mediaRequestHandler_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "DoOperation":
		return s.doOperation
	default:
		return nil
	}
}

func (s mediaRequestHandler_server_stub) doOperation(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 *model.AttachmentRequest
	a1 = serviceweaver_dec_ptr_AttachmentRequest_26f527db(dec)
	var a2 string
	a2 = dec.String()
	var a3 *model.AttachmentUpdateRequest
	a3 = serviceweaver_dec_ptr_AttachmentUpdateRequest_7d9aafff(dec)
	var a4 MediaRequestOperation
	*(*int)(&a4) = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.DoOperation(ctx, a0, a1, a2, a3, a4)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_Attachment_51e21580(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

type mediaRequestHandler_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that mediaRequestHandler_reflect_stub implements the MediaRequestHandler interface.
var _ MediaRequestHandler = (*mediaRequestHandler_reflect_stub)(nil)

func (s mediaRequestHandler_reflect_stub) DoOperation(ctx context.Context, a0 string, a1 *model.AttachmentRequest, a2 string, a3 *model.AttachmentUpdateRequest, a4 MediaRequestOperation) (r0 *model.Attachment, err error) {
	err = s.caller("DoOperation", ctx, []any{a0, a1, a2, a3, a4}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_AttachmentRequest_26f527db(enc *codegen.Encoder, arg *model.AttachmentRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeBinaryMarshaler(arg)
	}
}

func serviceweaver_dec_ptr_AttachmentRequest_26f527db(dec *codegen.Decoder) *model.AttachmentRequest {
	if !dec.Bool() {
		return nil
	}
	var res model.AttachmentRequest
	dec.DecodeBinaryUnmarshaler(&res)
	return &res
}

func serviceweaver_enc_ptr_AttachmentUpdateRequest_7d9aafff(enc *codegen.Encoder, arg *model.AttachmentUpdateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_AttachmentUpdateRequest_7d9aafff(dec *codegen.Decoder) *model.AttachmentUpdateRequest {
	if !dec.Bool() {
		return nil
	}
	var res model.AttachmentUpdateRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_ptr_Attachment_51e21580(enc *codegen.Encoder, arg *model.Attachment) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_Attachment_51e21580(dec *codegen.Decoder) *model.Attachment {
	if !dec.Bool() {
		return nil
	}
	var res model.Attachment
	(&res).WeaverUnmarshal(dec)
	return &res
}
