// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package model

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)

// weaver.InstanceOf checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.1 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Application)(nil)

type __is_Application[T ~struct {
	weaver.AutoMarshal
	ID           string "json:\"id,omitempty\""
	Name         string "json:\"name\""
	Website      string "json:\"website,omitempty\""
	RedirectURI  string "json:\"redirect_uri,omitempty\""
	ClientID     string "json:\"client_id,omitempty\""
	ClientSecret string "json:\"client_secret,omitempty\""
	VapidKey     string "json:\"vapid_key,omitempty\""
}] struct{}

var _ __is_Application[Application]

func (x *Application) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.Name)
	enc.String(x.Website)
	enc.String(x.RedirectURI)
	enc.String(x.ClientID)
	enc.String(x.ClientSecret)
	enc.String(x.VapidKey)
}

func (x *Application) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Application.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Name = dec.String()
	x.Website = dec.String()
	x.RedirectURI = dec.String()
	x.ClientID = dec.String()
	x.ClientSecret = dec.String()
	x.VapidKey = dec.String()
}

var _ codegen.AutoMarshal = (*Attachment)(nil)

type __is_Attachment[T ~struct {
	weaver.AutoMarshal
	ID               string     "json:\"id\""
	Type             string     "json:\"type\""
	URL              *string    "json:\"url\""
	TextURL          *string    "json:\"text_url\""
	PreviewURL       *string    "json:\"preview_url\""
	RemoteURL        *string    "json:\"remote_url\""
	PreviewRemoteURL *string    "json:\"preview_remote_url\""
	Meta             *MediaMeta "json:\"meta\""
	Description      *string    "json:\"description\""
	Blurhash         *string    "json:\"blurhash\""
	Sensitive        bool       "json:\"-\""
}] struct{}

var _ __is_Attachment[Attachment]

func (x *Attachment) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Attachment.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.Type)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.URL)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.TextURL)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.PreviewURL)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.RemoteURL)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.PreviewRemoteURL)
	serviceweaver_enc_ptr_MediaMeta_cdd23047(enc, x.Meta)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.Description)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.Blurhash)
	enc.Bool(x.Sensitive)
}

func (x *Attachment) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Attachment.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Type = dec.String()
	x.URL = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.TextURL = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.PreviewURL = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.RemoteURL = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.PreviewRemoteURL = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.Meta = serviceweaver_dec_ptr_MediaMeta_cdd23047(dec)
	x.Description = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.Blurhash = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.Sensitive = dec.Bool()
}

func serviceweaver_enc_ptr_string_3e89801b(enc *codegen.Encoder, arg *string) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.String(*arg)
	}
}

func serviceweaver_dec_ptr_string_3e89801b(dec *codegen.Decoder) *string {
	if !dec.Bool() {
		return nil
	}
	var res string
	res = dec.String()
	return &res
}

func serviceweaver_enc_ptr_MediaMeta_cdd23047(enc *codegen.Encoder, arg *MediaMeta) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_MediaMeta_cdd23047(dec *codegen.Decoder) *MediaMeta {
	if !dec.Bool() {
		return nil
	}
	var res MediaMeta
	(&res).WeaverUnmarshal(dec)
	return &res
}

var _ codegen.AutoMarshal = (*AttachmentUpdateRequest)(nil)

type __is_AttachmentUpdateRequest[T ~struct {
	weaver.AutoMarshal
	Description *string "form:\"description\" json:\"description\" xml:\"description\""
	Focus       *string "form:\"focus\" json:\"focus\" xml:\"focus\""
}] struct{}

var _ __is_AttachmentUpdateRequest[AttachmentUpdateRequest]

func (x *AttachmentUpdateRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("AttachmentUpdateRequest.WeaverMarshal: nil receiver"))
	}
	serviceweaver_enc_ptr_string_3e89801b(enc, x.Description)
	serviceweaver_enc_ptr_string_3e89801b(enc, x.Focus)
}

func (x *AttachmentUpdateRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("AttachmentUpdateRequest.WeaverUnmarshal: nil receiver"))
	}
	x.Description = serviceweaver_dec_ptr_string_3e89801b(dec)
	x.Focus = serviceweaver_dec_ptr_string_3e89801b(dec)
}

var _ codegen.AutoMarshal = (*MediaDimensions)(nil)

type __is_MediaDimensions[T ~struct {
	weaver.AutoMarshal
	Width     int     "json:\"width,omitempty\""
	Height    int     "json:\"height,omitempty\""
	FrameRate string  "json:\"frame_rate,omitempty\""
	Duration  float32 "json:\"duration,omitempty\""
	Bitrate   int     "json:\"bitrate,omitempty\""
	Size      string  "json:\"size,omitempty\""
	Aspect    float32 "json:\"aspect,omitempty\""
}] struct{}

var _ __is_MediaDimensions[MediaDimensions]

func (x *MediaDimensions) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MediaDimensions.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.Width)
	enc.Int(x.Height)
	enc.String(x.FrameRate)
	enc.Float32(x.Duration)
	enc.Int(x.Bitrate)
	enc.String(x.Size)
	enc.Float32(x.Aspect)
}

func (x *MediaDimensions) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MediaDimensions.WeaverUnmarshal: nil receiver"))
	}
	x.Width = dec.Int()
	x.Height = dec.Int()
	x.FrameRate = dec.String()
	x.Duration = dec.Float32()
	x.Bitrate = dec.Int()
	x.Size = dec.String()
	x.Aspect = dec.Float32()
}

var _ codegen.AutoMarshal = (*MediaFocus)(nil)

type __is_MediaFocus[T ~struct {
	weaver.AutoMarshal
	X float32 "json:\"x\""
	Y float32 "json:\"y\""
}] struct{}

var _ __is_MediaFocus[MediaFocus]

func (x *MediaFocus) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MediaFocus.WeaverMarshal: nil receiver"))
	}
	enc.Float32(x.X)
	enc.Float32(x.Y)
}

func (x *MediaFocus) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MediaFocus.WeaverUnmarshal: nil receiver"))
	}
	x.X = dec.Float32()
	x.Y = dec.Float32()
}

var _ codegen.AutoMarshal = (*MediaMeta)(nil)

type __is_MediaMeta[T ~struct {
	weaver.AutoMarshal
	Original MediaDimensions "json:\"original\""
	Small    MediaDimensions "json:\"small,omitempty\""
	Focus    *MediaFocus     "json:\"focus,omitempty\""
}] struct{}

var _ __is_MediaMeta[MediaMeta]

func (x *MediaMeta) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MediaMeta.WeaverMarshal: nil receiver"))
	}
	(x.Original).WeaverMarshal(enc)
	(x.Small).WeaverMarshal(enc)
	serviceweaver_enc_ptr_MediaFocus_2fe6dd21(enc, x.Focus)
}

func (x *MediaMeta) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MediaMeta.WeaverUnmarshal: nil receiver"))
	}
	(&x.Original).WeaverUnmarshal(dec)
	(&x.Small).WeaverUnmarshal(dec)
	x.Focus = serviceweaver_dec_ptr_MediaFocus_2fe6dd21(dec)
}

func serviceweaver_enc_ptr_MediaFocus_2fe6dd21(enc *codegen.Encoder, arg *MediaFocus) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_MediaFocus_2fe6dd21(dec *codegen.Decoder) *MediaFocus {
	if !dec.Bool() {
		return nil
	}
	var res MediaFocus
	(&res).WeaverUnmarshal(dec)
	return &res
}
